src: 
  url: http://example.org/source/
  authToken: srcsecret

dst: 
  url: http://example.org/destination/
  priority_id: 42
  status_id: 43
  tracker_id: 44
  project_id: 45
  attachments_url: http://example.org/attachments/
  attachments_dir: ~/Documents/attachments/
  mapping:
    alice: alicesecret
    clara: clarasecret
  default_token: defaultsecret
